### ISSUE TITLE
Any chance you would change the license to something where binary distributions don't have to have anything accompanying it?

### ISSUE THREAD

**Issue by xaxxon** [wjakob/filesystem#10]
I don't want to violate your copyright, but the chances I remember to put your information in my documetnation when I'm done seems low... 

Would you be willing to BSD this library?

**Comment by wjakob** [comment]
Sure, see https://github.com/wjakob/filesystem/blob/master/LICENSE

**Comment by xaxxon** [comment]
Sorry, I don't mean to be a nuisance, but it's this part I was referring to:

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

**Comment by wjakob** [comment]
This is the BSD license, no? See http://www.linfo.org/bsdlicense.html

**Comment by xaxxon** [comment]
you're absolutely right.   I'm really confused about the reproducing the copyright bit in binary form... Looking further.

**Comment by xaxxon** [comment]
Well, crap.   Now I need to go back through all the BSD stuff I've used and start putting together a attribution string in my program.  

Anyhow, thanks for trying to help a brother out :)   I'll just put in the attributions.   

At this point I don't care if you change the license back or not (though a standard license is probably easiest for the most people to use)
