### ISSUE TITLE
create_directory function is missing

### ISSUE THREAD

**Issue by rggjan** [wjakob/filesystem#3]

**Comment by rggjan** [comment]
Added a pull request. Only for windows so far, since I can't test mac / linux right now.

**Comment by xboi209** [comment]
bool create_directory(const path& p) {
    #ifdef WIN32
    		return CreateDirectoryW(p.wstr().c_str(), NULL) != 0 ? true : false;
    #else
    		return mkdir(p.str().c_str(), S_IRUSR | S_IWUSR | S_IXUSR) == 0 ? true : false;
    #endif
    }

**Comment by wjakob** [comment]
great, thanks! -- committed.
