### ISSUE TITLE
Ambiguous with C++17 std::filesystem

### ISSUE THREAD

**Issue by KIKI007** [wjakob/filesystem#34]
Hi Wenzel,

Is it possible to use Wenzel::filesystem replace the filesystem to avoid the ambiguity?

Best
Ziqi Wang

**Comment by Qix-** [comment]
This library doesn't intend to be compatible with std::filesystem. What is it you're asking for, exactly?

**Comment by KIKI007** [comment]
hi, thanks for the reply.

When I use Apple Clang with C++17 standard. Somehow the compiler confuses with the std::filesystem and this filesystem. Thus leading to a compiling error. So do you have any idea how to solve it?

Best
Ziqi Wang

**Comment by wjakob** [comment]
Hi Ziqi,

when using C++17 there is really no reason to depend on this project.  In fact. README.md states
```
This class is just a temporary workaround to avoid the heavy boost dependency until boost::filesystem is integrated into the standard template library at some point in the future.
```
(that point in the future has arrived :)).
-Wenzel
