### ISSUE TITLE
Make C++11 features optional.

### ISSUE THREAD

**Issue by IngwiePhoenix** [wjakob/filesystem#8]
I really want to use the library; but my target is MSVC 2010 and average OS X and Linux. Not everyone has the most recent compilers, especially people installing stuff through package managers :)

You can gracefully degrade code using `__cplusplus`:

- http://stackoverflow.com/questions/7530047/gnu-c-macro-cplusplus-standard-conform
- http://stackoverflow.com/questions/5047971/how-do-i-check-for-c11-support

**Comment by wjakob** [comment]
sorry, one of the points of this library is not to have workaround for old compilers. :-).
You can just use boost::filesystem if you really want C++03.

**Comment by IngwiePhoenix** [comment]
Ah, alright :).

Boost is usually really big, and I am only building a project of ~15 C++ files ( https://github.com/IngwiePhoenix/IceTea ). I managed to get STLPlus working for me - although wonky.

Thanks for your reply though!
